name: dl4hc
channels:
- peterjc123
- defaults
dependencies:
- python=3.5.5
- torch=1.8.*
- scipy
- pip
- pip:
  - dominate==2.3.1
  - git+https://github.com/pytorch/vision.git
  - Pillow==5.0.0
  - numpy==1.14.1
  - visdom==0.1.7
  - bm3d
  - opencv-python
